extends: default

ignore: |
  dist/

rules:
  line-length:
    max: 120
    allow-non-breakable-words: true
    allow-non-breakable-inline-mappings: true
  truthy:
    allowed-values: ["true", "false"]
  comments:
    min-spaces-from-content: 1
  document-start: disable
  quoted-strings:
    quote-type: any
    required: false
